CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  email VARCHAR(64) UNIQUE NOT NULL,
  password VARCHAR(64) NOT NULL,
  collection_id INTEGER UNIQUE NOT NULL
);

CREATE TABLE collections (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  book_count INTEGER NOT NULL
);

-- полная хуйня как будто бы но ок
CREATE TABLE collection_entry (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  collection_id INTEGER UNIQUE NOT NULL,
  book_id INTEGER UNIQUE NOT NULL
);
